name: Terraform CI/CD

on:
  push:
    paths:
      - 'tf/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Authenticate to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Terraform Init
      working-directory: tf
      run: terraform init

    - name: Terraform Plan
      working-directory: tf
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: tf
      run: terraform apply -auto-approve tfplan -lock=true