name: Terraform CI/CD

on:
  push:
    paths:
      - 'tf/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      working-directory: tf
      run: terraform init

    - name: Terraform Plan
      working-directory: tf
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: tf
      run: terraform apply -auto-approve tfplan -lock=true